name: XML-Feed
version: 0.03
abstract: XML Syndication Feed Support
author: Benjamin Trott <cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Class::ErrorHandler: 0
  Feed::Find: 0
  XML::RSS: 1.01
  XML::Atom: 0.08
  LWP: 0
  HTML::Parser: 0
  URI: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  List::Util: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.35
