abstract: XML Syndication Feed Support
author: Six Apart <cpan@sixapart.com>
build_requires:
  HTML::TokeParser: 0
  LWP: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: XML-Feed
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Class::ErrorHandler: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  Feed::Find: 0
  List::Util: 0
  URI::Fetch: 0
  XML::Atom: 0.08
  XML::RSS: 1.01
version: 0.09
